### ISSUE TITLE
Can't be installed from cocoapods

### ISSUE THREAD

**Issue by bitomule** [joshpc/ElasticPullToRefresh#3]
Seems like name is wrong or not pushed to cocoapods repo. I get this error:

```
[!] Unable to satisfy the following requirements:

- `ElasticPullToRefresh` required by `Podfile`
```

**Comment by joshpc** [comment]
Sorry! Fixed! About a year and a half late...

I definitely didn't see the notification for this, and didn't really need the project again until recently.
